### ISSUE TITLE
UART Bootloader?

### ISSUE THREAD

**Issue by evandavey** [hallard/LoRa-E5-Breakout#1]
Hi @hallard ,

My (original) LoRa E5 mini boards have arrived.  Have you looked into programming via UART (via USB) rather than requiring an ST-LINK?

**Comment by hallard** [comment]
Great you have it to play with.
No I didn’t tried but for that you need to setup the board into Seeed custom board bootloader starting/resetting the board pulling boot pin to low. Pay attention it’s not the original STM32 boot pin, it’s just a gpio tested in seeed firmware to put it into update mode.
But this is working only for seeed firmware once you erased original FW to flash again you need a external programmer except if you implement serial FW update in your code of course.

**Comment by evandavey** [comment]
OK thanks.  Posted in the SeeedStudio forums to see if anyone has written a bootloader which I guess has to set before user code on top of the STM32 DFU bootloader.

I guess the STM32 boot pin is not available then (looks like pin PH3)  Otherwise, couldn't we just put it into DFU mode and then use STM32CubeProgrammer.  A shame if Seeed hasn't broken that out as makes the E5 module a bit less usable.

SeeedStudio E5
![image](https://user-images.githubusercontent.com/552232/127291767-0b107e9a-4831-4e87-999d-a6fa09418de2.png)

STM32WLE5JC Datasheet Pinout
![image](https://user-images.githubusercontent.com/552232/127292008-dd58243c-42ca-4af5-bad7-3c470bef6ea7.png)

Pattern 13 according to https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf.

![image](https://user-images.githubusercontent.com/552232/127290784-12ed0fc3-2efe-4216-bf18-3d36962f1d51.png)

Possibly a software jump triggered by the fake boot pin following this?  That wouldn't be so bad if that's all that would need to be included in user code.
https://stm32f4-discovery.net/2017/04/tutorial-jump-system-memory-software-stm32/

https://github.com/markusgritsch/SilF4ware/blob/master/SilF4ware/drv_reset.c

**Comment by hallard** [comment]
Yes it’s not exposed but not sure to understand the issue, I have no problem flashing the device using stlink v3 mod (7€) with swio, swclk, rst pins

**Comment by hallard** [comment]
If you want to flash with serial something interesting here https://www.st.com/resource/en/application_note/cd00264342-usart-protocol-used-in-the-stm32-bootloader-stmicroelectronics.pdf

**Comment by evandavey** [comment]
Yep - will be able to flash it that way but that means a debugger always connected and less convienient (particularly for low power measurements as the debugger probably needs to be disconnected each time).  Also makes it less accessible as a product.  For example, getting a non-technical user to upload firmware (much easier for them to just plug into USB then run an update script).

A software jump seems the most promising option to get back into STM32 DFU.  So hoping, I could use the ST-LINK for the initial load and then software jump on the fake boot pin.  I don't think this is what the SeeedStudio code is doing as I get nothing in STM32Programmer on UART trying that.

**Comment by evandavey** [comment]
Regarding the link, the trick is getting it into DFU mode first (then STM32CubeProgrammer can use UART via this protocol so we don't need to worry about that).  But maybe this is implying you can send 0x7F on boot to kick it into DFU, will dig a bit deeper (nope, looks like that sequence is after DFU).

![image](https://user-images.githubusercontent.com/552232/127295384-f62d3957-937b-408d-b2de-5953602685e6.png)

**Comment by hallard** [comment]
Oh I see, FYI when we discussed on Mbed issue about low power my measurement were taken within jtag connected pins io, clk, rst and never changed consumption to my surprise and it flash so quick that I never changed mode, but I have a secret I give end user a custom board that makes flash so easy 

![F5489E54-5EE1-4CB8-90A5-82E0A9B6E451](https://user-images.githubusercontent.com/2471931/127296685-af582b87-4b00-4491-9ac3-b3ec01dbad7b.jpeg)

**Comment by hallard** [comment]
In all case it’s a shame real boot pin not exposed on RAK it is. May be as you stated is to setup this mode by software if it’s possible of course

**Comment by evandavey** [comment]
Ah, nice.  I will try with the ST-LINK tomorrow.  I'll admit I jumped straight to UART as I hoped it would be that straight-forward (and programming via USB is really the way any modern board should work).  If I get adventurous I might peek under the can of the module but maybe they prioritised other functionality with limited pins available.
