### ISSUE TITLE
low tx power

### ISSUE THREAD

**Issue by m0rphex** [hallard/LoRa-E5-Breakout#3]
Hi and thank you for your work with the LoRa E5. I'm using mbed os and mbed studio with the LORA_E5_MINI target which is the board I have at hand. I can build and flash the lorawan example code, but the device is transmitting at a very low power. Also when I join TTN with my own forwarder gateway the packet transmission interval is ~6 seconds with duty cycle enabled (too fast). I'm wondering whether there is a problem with the antenna RF switching and other declarations. Which version of mbed os have you used with the e5 breakout board. Any insight into this would be much appreciated.

**Comment by hallard** [comment]
@m0rphex you need to use version 6.15 (with power fix, but that does not seems to be optimal because of hardware design) but if you need more power, use version 6.14 (before my patch) to see this [PR](https://github.com/ARMmbed/mbed-os/pull/15017)

Also use latest` stm32customtargets` as indicated in the readme. Best would be you post your `mbed_app.json` file to see

**Comment by m0rphex** [comment]
@hallard thank you for the prompt answer. I've tried mbed 6.14 without any difference in tx power, its still too low when I monitor my sdr dongle. I'm able to get proper output with the seeed studio LoRaWAN node example and AT firmware. I don't have exact measurements but the tx seems to be well below 14dBm. Could you point out where I could have a look at configuring the PA settings. It's been a few years since I last used mbed os, much has changed :) What kind of RSSI values have you been getting with the mbed LoRaWAN example and the E5 Breakout? My mbed_app.json is not modified, ive tried the LORA_E5_BREAKOUT overrides, but I don't think that's the problem here.

**Comment by hallard** [comment]
Do you have setup `RBI_CONF_RFO_HP` in `mbed_conf.json` as an example below?

```json
"target_overrides": {
        "*": {
            "stm32wl-lora-driver.rf_switch_config": "RBI_CONF_RFO_HP",
            "stm32wl-lora-driver.debug_rx": "LED1",
            "stm32wl-lora-driver.debug_tx": "LED2",
            "stm32wl-lora-driver.debug_invert": 1,
            "lora.over-the-air-activation": true,
            "lora.duty-cycle-on": true,
            "lora.phy": "EU868",
        },
```

As far as I remember, node near GW got RSSI between -40/-30

**Comment by Mircerson** [comment]
Hi, 
Had the same issue, I was using mbed 6.15.1
You need "stm32wl-lora-driver.rf_switch_config": "RBI_CONF_RFO_HP" in the mbed_conf.json file ;) 

Without this setting, I was getting like 4-5 m from the gateway:
![MbedOsData](https://user-images.githubusercontent.com/83925805/159055253-58d31c16-6944-4de9-914a-cf2928c2d3f2.PNG)
After enabling it and moving a few things around ( mind you I am only using The Things Indoor Gateway ):
![CubeData](https://user-images.githubusercontent.com/83925805/159055911-adf355e3-c4fc-4485-8fed-8780cfe11ab2.PNG)

**Comment by m0rphex** [comment]
Thank you `"stm32wl-lora-driver.rf_switch_config": "RBI_CONF_RFO_HP"` solved the issue!

**Comment by hallard** [comment]
thanks for the headup, I've updated the read me file according to.
